### ISSUE TITLE
Impossible to reset a variable

### ISSUE THREAD

**Issue by C4Grey** [PebbleTemplates/pebble#201] opened 2016-05-21 12:56 UTC
Variables inside templates cannot be reseted(although it is available in Twig), for example:
````code=twig
{% set total = 0 %}
{% for item in items %}
     {% set total = total + item.balance %}
{% endfor %}
Balance: {{ total }}
````
The "total" variable will be equal to 0 in the last line.
P.S.
It seems like a variable can be reseted outside a cycle, so maybe this issue is related to scoping.

**Comment by sunnypav** [comment] 2016-05-25 21:48
I have also encountered the same issue which is working totally fine in Twig. Please fix.

**Comment by sunnypav** [comment] 2016-05-25 21:50
I am also facing this issue which is totally working fine in Twig. Please fix.

**Comment by stanislas-m** [comment] 2016-05-26 06:16
I can't reproduce this problem with this test:

```java
@Test
public void testReSetInForLoop() throws PebbleException, IOException {
    PebbleEngine pebble = new PebbleEngine.Builder().loader(new StringLoader()).strictVariables(false).build();

    String source = "{% set total = 0 %}{% for item in items %}{% set total = total + item.balance %}{% endfor %}{{ total }}";
    PebbleTemplate template = pebble.getTemplate(source);
    Map<String, Object> context = new HashMap<>();
    List<Map<String,Object>> items = new ArrayList<>();
    for (int i = 1; i < 4 ; ++i) {
        Map<String, Object> item = new HashMap<>();
        item.put("balance", i);
        items.add(item);
    }
    context.put("items", items);

    Writer writer = new StringWriter();
    template.evaluate(writer, context);
    assertEquals("6", writer.toString());
}
```

Do you have more details about the context?

**Comment by C4Grey** [comment] 2016-06-30 10:38
I am sorry for late response, moved to another project for a while...well, here are some details:
- Spring Boot 1.4.0.M1
- Pebble added via the com.mitchellbosecke:pebble-spring-boot-starter:2.2.1 dependency
- com.mitchellbosecke.pebble.loader.FileLoader used for templates loading
- Caching disabled

**Comment by toby-allsopp** [comment] 2016-07-13 03:10
Try nesting inside another for loop. This code in ForNode.java is responsible for this behaviour, I think:

```
            /*
             * Only if there is a variable name conflict between one of the
             * variables added by the for loop construct and an existing
             * variable do we push another scope, otherwise we reuse the current
             * scope for performance purposes.
             */
            if (scopeChain.currentScopeContainsVariable("loop") || scopeChain
                    .currentScopeContainsVariable(variableName)) {
                scopeChain.pushScope();
                newScope = true;
            }
```

**Comment by toby-allsopp** [comment] 2016-07-13 05:08
This test reproduces the problem:

```
    @Test
    public void testReSetInForLoop() throws PebbleException, IOException {
        PebbleEngine pebble = new PebbleEngine.Builder().loader(new StringLoader()).strictVariables(false).build();

        String source = "{% set total = 0 %}{% for i in 1..1 %}{% for item in items %}{% set total = total + item.balance %}{% endfor %}{% endfor %}{{ total }}";
        PebbleTemplate template = pebble.getTemplate(source);
        Map<String, Object> context = new HashMap<>();
        List<Map<String,Object>> items = new ArrayList<>();
        for (int i = 1; i < 4 ; ++i) {
            Map<String, Object> item = new HashMap<>();
            item.put("balance", i);
            items.add(item);
        }
        context.put("items", items);

        Writer writer = new StringWriter();
        template.evaluate(writer, context);
        assertEquals("6", writer.toString());
    }
```

I'll submit a PR shortly.

**Comment by mbosecke** [comment] 2016-09-22 02:59
Pull request has been merged

**Closed by mbosecke** 2016-09-22 02:59 UTC
