### ISSUE TITLE
Parser regression with operators vs. names

### ISSUE THREAD

**Issue by axeld** [PebbleTemplates/pebble#426] opened 2019-02-04 13:34 UTC
I have a custom operator named "matches". In Pebble 2.x I could still have a named attribute called "matches", too. This now results in a parse error in 3.x:
`
com.mitchellbosecke.pebble.error.ParserException: Unexpected token of value "matches" and type OPERATOR, expected token of type NAME (..\template.html:1)
	at com.mitchellbosecke.pebble.lexer.TokenStream.expect(TokenStream.java:73)
`

**Comment by ebussieres** [comment] 2019-02-06 13:33
Please provide a test case

**Comment by axeld** [comment] 2019-02-06 14:35
I was afraid that this would happen :-)

However, I've looked into the issue, and it seems c7fa574d3e5463d6f6fee71562df6b1416ffec15 is the culprit. It effectively prevents having a name with the same identifier as an operator (LexerImpl::lexExpression tests operators first, and only knows a single truth).

I guess it's just something that one must decide if it's a desirable feature or not. If not, it would be nice if this would be prevented from happening during engine initialization, and not during runtime.

**Comment by bjansen** [comment] 2019-07-13 13:43
I suppose we could check if the token matches `com.mitchellbosecke.pebble.lexer.LexerImpl#REGEX_NAME` instead of requiring the token to be a `com.mitchellbosecke.pebble.lexer.Token.Type#NAME`. That would fix your problem.

**Comment by bjansen** [comment] 2019-07-13 14:05
But it means this kind of code would become valid:
```mustache
{% for is in myList %}
  {% if is is null %} ...
{% endfor %}
```

Do we want that?

**Comment by bjansen** [comment] 2019-07-13 14:13
Pebble won't even let me *use* such a variable once it's defined. Could you provide an example that used to work with your custom operator?

**Comment by ebussieres** [comment] 2019-07-13 14:20
I don't think that keywords should be allowed to be used as a variable. Like in any other language.

**Comment by bjansen** [comment] 2019-07-13 14:22
Right, but @axeld is asking for *operators*, not *keywords* :). Although I agree this is not a great idea, as it could lead to confusing code.

**Comment by axeld** [comment] 2019-09-30 10:03
It's more like a case of allowing matches as variable and matches as method as the same time, which for example Java allows for.
But since I already adapted my code, I'm fine either way, so feel free to close it if you think it would be awkward ;-)

**Comment by sampart** [comment] 2019-11-25 17:08
I've seen this problem, but where only the **beginning** of the variable name is an operator:

```
<option value="" {{ is_a_filter_selected ? "" : "selected" }}></option>
```

gives

```
HTTP ERROR 500

Problem accessing /path/here/. Reason:

    Server Error

Caused by:

java.lang.ExceptionInInitializerError
[...]
Caused by: com.mitchellbosecke.pebble.error.ParserException: Unexpected token "OPERATOR" of value "is" (paht/here/my_file.peb:36)
```

Renaming the variable to `a_filter_is_selected` solved the problem in this example.

**Comment by ebussieres** [comment] 2020-11-17 22:37
Duplicate of #518

**Closed by ebussieres** 2020-11-17 22:37 UTC
