### ISSUE TITLE
The value of the parameter passed to the child template is cast to a String

### ISSUE THREAD

**Issue by logue** [PebbleTemplates/pebble#506] opened 2020-04-30 03:42 UTC
An error occurs when  send an object to a child template with the with statement of include.
```
{% include 'partial/summary' with {post: post} %}
```
At this time, when trying to cast the value of post to the String type, an error of `class dev.logue.app.models.Post cannot be cast to class java.lang.String` occurs.

The contents of the post are as follows:

```
Model: dev.logue.app.models.Post, table: 'posts', attributes: {body=Post body, created_at=2020-04-15 18:27:15.0, id=2, title=Post title, updated_at=2020-04-24 16:41:17.0}
```

Note: dev.logue.app.models.Post is child class of [org.javalite.activejdbc.Model](http://javalite.github.io/2.3.2-j8-SNAPSHOT/org/javalite/activejdbc/Model.html). 

Also, it seems that the model values cannot be expanded normally. When fetching the `title`, the value cannot be fetched without using the method like `post.get('title')` instead of `post.title`. At least JTwig was able to get the value correctly this way.

**Comment by ebussieres** [comment] 2020-05-03 17:21
@logue Can you submit a unit test to demonstrate your issue please ?

**Comment by ebussieres** [comment] 2020-05-03 19:17
@logue I created a unit test and I can't reproduce your problem. https://github.com/PebbleTemplates/pebble/commit/09cad2afbe3fda7f42d0b10d6dfee9cd8d8acff8

**Comment by ebussieres** [comment] 2020-05-21 00:19
Due to absence of response, I'll close it. You can reopen it if you wish

**Closed by ebussieres** 2020-05-21 00:19 UTC
