### ISSUE TITLE
Changing caching library

### ISSUE THREAD

**Issue by robertotru** [PebbleTemplates/pebble#238] opened 2016-11-11 14:14 UTC
After reading the release notes of SpringBoot 1.4.0 (see https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-1.4-Release-Notes ), it seems that Spring guys suggested to use a new caching library, i.e. Caffeine ( https://github.com/ben-manes/caffeine ) instead of the caching libraries from Guava. 
Replacement is easy.
Do you think you would consider a pull request with the aforementioned change?

**Comment by mbosecke** [comment] 2016-11-13 21:56
Closing as duplicate of #155. 

But yes, I would love to switch to Caffeine. If you decide to help with this, it should be done off the "3.0" branch.

**Closed by mbosecke** 2016-11-13 21:56 UTC

**Comment by robertotru** [comment] 2016-11-13 21:57
@mbosecke agreed! I'll do it this week

**Comment by robertotru** [comment] 2016-11-13 23:00
@mbosecke I have a question. Caffeine is for Java8 only, while I see that Pebble's branch 3.0 has target 1.7. Do you plan to move to Java8 in version 1.7? Otherwise, there is no way to use that caching library.

**Comment by mbosecke** [comment] 2016-11-13 23:09
Yup, I was planning on moving to Java 8 for the next major release of Pebble so feel free to up that target number.

**Comment by thclev** [comment] 2017-04-10 21:16
Caffeine has a Guava wrapper. Can't that be used for now?

**Comment by ben-manes** [comment] 2017-04-10 23:16
@thclev It looks like migration was done in #239
