### ISSUE TITLE
Introduce a Cache abstraction

### ISSUE THREAD

**Issue by slandelle** [PebbleTemplates/pebble#294] opened 2017-09-21 16:41 UTC
Hi,

Guava is a tricky dependency. Large projects can have multiple dependencies to libraries that depend on different Guava versions and cause conflicts.

I see there's a plan to switch to Caffeine (great!) for Pebble 3.0, but I guess this means in a pretty far future.

Instead, would you be interested in a contribution to introduce a cache abstraction, with Guava and Caffeine based implementations (Caffeine only being an optional dependency)?
This way, Guava would still be the default, at least in Pebble 2, but users could prefer passing Caffeine based caches instead and exclude the Guava dependency.

Please let me know.

**Comment by slandelle** [comment] 2017-09-27 20:13
@ebussieres @mbosecke Gentle ping :)

**Comment by slandelle** [comment] 2017-10-03 06:10
So actually, as Caffeine uses Java 8, it would be complicated to have such an API without upgrading first.
Would you be interested in upgrading in Pebble 1.5 without waiting for 2.0? Or releasing beta versions of 2.0?

FYI, as I didn't get any answer to my messages and really needed to move forward with this issue and #293, I had no choice but [to fork](https://github.com/gatling/pebble). I would really love to be able to contribute my changes back instead of forking... Please answer.

**Comment by ben-manes** [comment] 2017-10-03 06:13
Since caffeine has guava adapters, could that be the abstraction that is implemented based on the jdk version? Might be easiest.

**Comment by slandelle** [comment] 2017-10-03 07:59
@ben-manes Did you hack Google's robots so they would notify you of every new mention of Caffeine on Github? ;-)

> Since caffeine has guava adapters, could that be the abstraction that is implemented based on the jdk version? Might be easiest.

The point is to no longer depend on Guava, hence not expose it in the Pebble API.

IMHO, Guava must go away:

1. It's legacy

* Functions? Use Java 8
* Fluent collections? Use Java 8's Streams
* Immutable and primitive collections? Use Eclipse collections
* Cache? Use Caffeine

2. It's a cancer

The issue here is not because of Guava itself but because of library maintainers who miss the point that Guava will release a new major version every 4 months or so, hence with breaking changes. You're supposed to keep your Guava dep up to date, otherwise you'll ruin large projects. For example, Pebble depends on 16.0.1 that was released almost 4 years ago.

As Guava is popular, you can easily end up with conflicting dependency versions. In my case, I pull Guava from Pebble, Openstack, Cassandra Java driver and cassandra-unit.
If you're unlucky and can't find a version that's compatible with all your deps, you have to:
* either contribute an upgrade to all your deps and hope maintainers will accept to merge and release
* or fork
* or build fatjars that ship Guava in a translated package

**Comment by ben-manes** [comment] 2017-10-03 09:03
Projects not updating their dependencies despite modern tooling is frustrating, since libraries should be allowed to evolve. Guava did change the policy to no longer break backwards compatibility after 2 year depreciation cycle so hopefully this issue will be reduced in the future. It’s still useful, but you’re right that it’s much less so these days. I do think libraries should minimize their dependencies do to conflict issues and upgrade regularly. Seems to make sense to remove Guava here.

GitHub search is great and super easy to monitor keywords with :)

**Comment by slandelle** [comment] 2017-10-03 09:06
> Seems to make sense to remove Guava here.

I think so too. Pebble only depend on Guava for caching, Caffeine is simply better than Guava cache and if one really want to use Guava cache, he can use the adapter.

**Comment by marcban** [comment] 2017-10-12 16:49
I agree! Having recently added Pebble to my project, Guava is now my biggest dependency by far (almost 2Mb), and I prefer cache2k for caching

**Comment by nicky9door** [comment] 2018-01-04 16:03
So I did a quick implementation of a cache abstraction [here](https://github.com/nicky9door/pebble/tree/cache-abstraction), with the specific commit being [here](https://github.com/nicky9door/pebble/commit/af32f8f586600d865b3e5936f84b1382dbcca6e4).  All the tests run successfully.

Somethings of note:
  * Interface is provided a Callable which can be used to create the template if not present in the cache
  * Implemented a NOOP cache which invokes the callable every time
  * Changed the default cache to one backed by a ConcurrentHashMap
    * The ConcurrentHashMap cache is NOT synchronized with respect to compiling the template.  So there might be a race condition when compiling a template but I'm not sure whether making the compilation synchronized would introduce unnecessary performance penalties
  * The Guava cache throws RuntimeExceptions verbatim but wraps checked exceptions in an ExecutionException.  The pebble engine would check the cause of the ExecutionException and unwrap it if the cause was a PebbleException.  Since other caching libraries may handle exceptions differently, I changed the try/catch to rethrow RuntimeException and PebbleException.  All other checked exceptions will operate as it does now (check the cause for PebbleException and rethrow if found). 

I'm considering making a PR but considering this is a breaking change, I'm not sure whether this should be moved to version 3.  Furthermore, considering #293 and some of the commits made by @slandelle to address it, there may need to be some adjustments made with respect to the types used for the cache keys

**Comment by slandelle** [comment] 2018-01-04 16:10
@nicky9door you should be using CHM#computeIfAbsent if running on Java 8 to avoid the race condition you mentionned.

**Comment by nicky9door** [comment] 2018-01-04 16:42
@slandelle Since pebble is still on Java 7, I couldn't use computeIfAbsent.  If the project is moving to Java 8, this is indeed the best solution

**Comment by slandelle** [comment] 2018-01-05 08:34
@nicky9door IMHO, dropping Java 7 support would be the way to go for the next release here. Sadly, there's a chance this project is dead, see #311 .

**Comment by hectorlf** [comment] 2018-03-05 00:32
I'm not familiar with the plans for Pebble 3, but for the current release this is still a no go. See #155

**Comment by mach-kernel** [comment] 2018-03-20 15:58
I am in support of @nicky9door's changes and think it would be beneficial if they could be PR'd and move forward (along with the Java 7 deprecation). GAE now supports Java 8 and it doesn't seem that there is any other real impediment (i.e. legacy users can still use the older version if they wish).

**Comment by ebussieres** [comment] 2018-04-08 11:50
We're gonna use caffeine in v3. Already done in branch 3.0

**Closed by ebussieres** 2018-04-08 11:50 UTC
